# Project: Test_V1
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = main.o printf_out.o out.o quote.o TimeDate.o
LINKOBJ  = main.o printf_out.o out.o quote.o TimeDate.o
LIBS     = -L"D:/Dev_c++/Dev-Cpp/MinGW64/lib" -L"D:/Dev_c++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"D:/Dev_c++/Dev-Cpp/MinGW64/include" -I"D:/Dev_c++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Dev_c++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/Dev_c++/Dev-Cpp/MinGW64/include" -I"D:/Dev_c++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Dev_c++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/Dev_c++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Test_V1.exe
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

printf_out.o: printf_out.cpp
	$(CPP) -c printf_out.cpp -o printf_out.o $(CXXFLAGS)

out.o: out.cpp
	$(CPP) -c out.cpp -o out.o $(CXXFLAGS)

quote.o: quote.cpp
	$(CPP) -c quote.cpp -o quote.o $(CXXFLAGS)

TimeDate.o: TimeDate.cpp
	$(CPP) -c TimeDate.cpp -o TimeDate.o $(CXXFLAGS)
